version: "3.9"
services:
  api:
    env_file:
      - .env
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env