version: "3.9"
services:
  api:
    container_name: api_container
    env_file:
      - .env
    build: .
    depends_on:
      - db
      - test_db
    ports:
      - "8000:8000"
  db:
    container_name: db_container
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  test_db:
    container_name: testing_db
    image: postgres
    ports:
      - "5433:5433"
    command: -p 5433
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_USER_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}